# Generated by Django 4.0.4 on 2022-04-20 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.CharField(max_length=55)),
                ('hdd', models.IntegerField()),
                ('data', models.IntegerField()),
                ('support', models.CharField(max_length=55)),
                ('theme', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='HostProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_data', to='core.options')),
                ('hdd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_hdd', to='core.options')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_panel', to='core.options')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_support', to='core.options')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.options')),
            ],
        ),
    ]
