# Generated by Django 4.0.4 on 2022-04-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_hdd_hostproduct_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostproduct',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
